In [ ]:
# !pip install giza-datasets

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
# import certifi
# import os
# os.environ['SSL-CERT_FILE'] = certifi.where()
# from giza_datasets import DatasetsLoader
# import pandas as pd


# loader = DatasetsLoader()
# df1 = loader.load("gora-competition-training")
# df = pd.DataFrame(df1.to_pandas())

In [ ]:
df.head()

,address,total_borrow,count_borrow,avg_borrow_amount,std_borrow_amount,first_borrow_date,token_borrow_mode,borrow_amount_cv,total_repay,count_repay,...,net_deposits_to_total_redeemed,avg_liquidation_to_avg_borrow,dex_total_sum_added,dex_total_sum_removed,dex_total_sum_swapped,liquidated,calc_start_time,added_at,total_liquidation_to_total_borrow,__index_level_0__
0,0x3266424c9bee709ef24965b0ddfdc504cb382a2a,19.039084,18,1.057727,2.268998,2022-05-07,USDC,2.145165,0.100039,1.0,...,0.424938,0.000000,0.0,0.0,0.0,0.0,2023-02-04 16:06:12.097,2023-02-04 16:09:32.485,0.000000,269840
1,0xae26d5f10a1790c85b91fd79e18dd2de785d0636,0.140274,1,0.140274,0.000000,2022-08-02,usdc,0.000000,0.000000,0.0,...,0.182521,0.970264,0.0,0.0,0.0,1.0,2023-03-01 16:06:24.346,2023-03-01 16:11:22.942,0.970264,723218
2,0x38a0c07f7288872eb759534af7514960a6fcc1a5,9.020736,1,9.020736,0.000000,2022-11-21,usdc,0.000000,0.000000,0.0,...,1.820265,1.006330,0.0,0.0,0.0,1.0,2023-02-03 16:06:11.043,2023-02-03 16:18:48.896,1.006330,261348
3,0xe90fafe58deb3b262e710d43f1912c28948475c9,20.050150,1,20.050150,0.000000,2022-08-27,USDC,0.000000,20.007832,1.0,...,78.856029,0.000000,0.0,0.0,0.0,0.0,2023-02-05 16:06:16.899,2023-02-05 16:16:27.687,0.000000,294147
4,0x212944bff1143bf7d24a2f4a2d23f906483cc2fd,0.000100,1,0.000100,0.000000,2022-09-06,USDC,0.000000,0.000000,0.0,...,13.051750,0.000000,0.0,0.0,0.0,0.0,2023-01-18 21:18:42.947,2023-01-19 07:01:39.016,0.000000,16998

In [ ]:
df.shape

(783322, 50)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 783322 entries, 0 to 783321
Data columns (total 50 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   address                            783322 non-null  object
 1   total_borrow                       783322 non-null  float64
 2   count_borrow                       783322 non-null  int64
 3   avg_borrow_amount                  783322 non-null  float64
 4   std_borrow_amount                  783322 non-null  float64
 5   first_borrow_date                  783322 non-null  object
 6   token_borrow_mode                  783322 non-null  object
 7   borrow_amount_cv                   783322 non-null  float64
 8   total_repay                        783322 non-null  float64
 9   count_repay                        783322 non-null  float64
 10  avg_repay_amount                   783322 non-null  float64
 11  std_repay_amount                   783322 non-null  float64
 12  repay_amount_cv                    783322 non-null  float64
 13  total_deposit                      783322 non-null  float64
 14  count_deposit                      783322 non-null  float64
 15  avg_deposit_amount                 783322 non-null  float64
 16  std_deposit_amount                 783322 non-null  float64
 17  deposit_amount_cv                  783322 non-null  float64
 18  total_redeem                       783322 non-null  float64
 19  count_redeem                       783322 non-null  float64
 20  avg_redeem_amount                  783322 non-null  float64
 21  std_redeem_amount                  783322 non-null  float64
 22  redeem_amount_cv                   783322 non-null  float64
 23  total_liquidation                  783322 non-null  float64
 24  count_liquidation                  783322 non-null  float64
 25  avg_liquidation_amount             783322 non-null  float64
 26  std_liquidation_amount             783322 non-null  float64
 27  liquidation_amount_cv              783322 non-null  float64
 28  days_since_first_borrow            783322 non-null  float64
 29  net_outstanding                    783322 non-null  float64
 30  int_paid                           783322 non-null  float64
 31  net_deposits                       783322 non-null  float64
 32  count_repays_to_count_borrows      783322 non-null  float64
 33  avg_repay_to_avg_borrow            783322 non-null  float64
 34  net_outstanding_to_total_borrowed  783322 non-null  float64
 35  net_outstanding_to_total_repaid    783322 non-null  float64
 36  count_redeems_to_count_deposits    783322 non-null  float64
 37  total_redeemed_to_total_deposits   783322 non-null  float64
 38  avg_redeem_to_avg_deposit          783322 non-null  float64
 39  net_deposits_to_total_deposits     783322 non-null  float64
 40  net_deposits_to_total_redeemed     783322 non-null  float64
 41  avg_liquidation_to_avg_borrow      783322 non-null  float64
 42  dex_total_sum_added                783322 non-null  float64
 43  dex_total_sum_removed              783322 non-null  float64
 44  dex_total_sum_swapped              783322 non-null  float64
 45  liquidated                         783322 non-null  float64
 46  calc_start_time                    783322 non-null  object
 47  added_at                           783322 non-null  object
 48  total_liquidation_to_total_borrow  783322 non-null  float64
 49  __index_level_0__                  783322 non-null  int64
dtypes: float64(43), int64(2), object(5)
memory usage: 298.8+ MB

In [ ]:
df.isnull().sum()

address                              0
total_borrow                         0
count_borrow                         0
avg_borrow_amount                    0
std_borrow_amount                    0
first_borrow_date                    0
token_borrow_mode                    0
borrow_amount_cv                     0
total_repay                          0
count_repay                          0
avg_repay_amount                     0
std_repay_amount                     0
repay_amount_cv                      0
total_deposit                        0
count_deposit                        0
avg_deposit_amount                   0
std_deposit_amount                   0
deposit_amount_cv                    0
total_redeem                         0
count_redeem                         0
avg_redeem_amount                    0
std_redeem_amount                    0
redeem_amount_cv                     0
total_liquidation                    0
count_liquidation                    0
avg_liquidation_amount               0
std_liquidation_amount               0
liquidation_amount_cv                0
days_since_first_borrow              0
net_outstanding                      0
int_paid                             0
net_deposits                         0
count_repays_to_count_borrows        0
avg_repay_to_avg_borrow              0
net_outstanding_to_total_borrowed    0
net_outstanding_to_total_repaid      0
count_redeems_to_count_deposits      0
total_redeemed_to_total_deposits     0
avg_redeem_to_avg_deposit            0
net_deposits_to_total_deposits       0
net_deposits_to_total_redeemed       0
avg_liquidation_to_avg_borrow        0
dex_total_sum_added                  0
dex_total_sum_removed                0
dex_total_sum_swapped                0
liquidated                           0
calc_start_time                      0
added_at                             0
total_liquidation_to_total_borrow    0
__index_level_0__                    0
dtype: int64

In [ ]:
df.describe()

,total_borrow,count_borrow,avg_borrow_amount,std_borrow_amount,borrow_amount_cv,total_repay,count_repay,avg_repay_amount,std_repay_amount,repay_amount_cv,...,avg_redeem_to_avg_deposit,net_deposits_to_total_deposits,net_deposits_to_total_redeemed,avg_liquidation_to_avg_borrow,dex_total_sum_added,dex_total_sum_removed,dex_total_sum_swapped,liquidated,total_liquidation_to_total_borrow,__index_level_0__
count,7.833220e+05,783322.000000,7.833220e+05,783322.000000,783322.000000,7.833220e+05,783322.000000,7.833220e+05,783322.000000,783322.000000,...,7.833220e+05,783322.000000,7.833220e+05,783322.000000,783322.0,783322.0,783322.0,783322.000000,783322.000000,7.833220e+05
mean,6.033347e+03,11.778749,2.344247e+02,242.959980,1.442197,5.550964e+03,4.115828,2.609501e+02,238.722945,0.623140,...,9.019779e+02,-113.007873,2.737097e+02,0.557274,0.0,0.0,0.0,0.215671,0.132184,5.091820e+05
std,1.680525e+05,15.245985,9.115010e+03,6109.928866,1.412328,1.614440e+05,11.088226,9.158955e+03,4696.365759,0.890489,...,4.597125e+04,6271.526552,1.602028e+04,2.453003,0.0,0.0,0.0,0.411287,0.320387,2.944697e+05
min,1.000000e-12,1.000000,1.000000e-12,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,...,0.000000e+00,-706950.252662,-9.999986e-01,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.000000e+00
25%,6.618732e-02,1.000000,2.083023e-02,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,...,0.000000e+00,0.464784,1.145047e-01,0.000000,0.0,0.0,0.0,0.000000,0.000000,2.539652e+05
50%,1.488423e+00,6.000000,2.211536e-01,0.069441,1.225045,9.999503e-02,1.000000,4.414827e-02,0.000000,0.000000,...,6.867271e-02,0.988364,1.074616e+00,0.000000,0.0,0.0,0.0,0.000000,0.000000,5.082325e+05
75%,1.593537e+01,20.000000,2.500000e+00,2.038590,2.233169,1.000349e+01,4.000000,1.866427e+00,0.739240,1.246357,...,1.968527e+00,1.000000,6.326215e+00,0.000000,0.0,0.0,0.0,0.000000,0.000000,7.635108e+05
max,1.795176e+07,732.000000,1.567741e+06,696907.961050,6.751410,1.794177e+07,580.000000,1.567741e+06,404424.843263,6.629086,...,4.137916e+06,1.000000,5.213832e+06,46.797406,0.0,0.0,0.0,1.000000,5.469605,1.019888e+06

In [ ]:
df.columns

Index(['address', 'total_borrow', 'count_borrow', 'avg_borrow_amount',
       'std_borrow_amount', 'first_borrow_date', 'token_borrow_mode',
       'borrow_amount_cv', 'total_repay', 'count_repay', 'avg_repay_amount',
       'std_repay_amount', 'repay_amount_cv', 'total_deposit', 'count_deposit',
       'avg_deposit_amount', 'std_deposit_amount', 'deposit_amount_cv',
       'total_redeem', 'count_redeem', 'avg_redeem_amount',
       'std_redeem_amount', 'redeem_amount_cv', 'total_liquidation',
       'count_liquidation', 'avg_liquidation_amount', 'std_liquidation_amount',
       'liquidation_amount_cv', 'days_since_first_borrow', 'net_outstanding',
       'int_paid', 'net_deposits', 'count_repays_to_count_borrows',
       'avg_repay_to_avg_borrow', 'net_outstanding_to_total_borrowed',
       'net_outstanding_to_total_repaid', 'count_redeems_to_count_deposits',
       'total_redeemed_to_total_deposits', 'avg_redeem_to_avg_deposit',
       'net_deposits_to_total_deposits', 'net_deposits_to_total_redeemed',
       'avg_liquidation_to_avg_borrow', 'dex_total_sum_added',
       'dex_total_sum_removed', 'dex_total_sum_swapped', 'liquidated',
       'calc_start_time', 'added_at', 'total_liquidation_to_total_borrow',
       '__index_level_0__'],
      dtype='object')

In [ ]:
import pandas as pd
import plotly.graph_objs as go
from plotly.subplots import make_subplots

In [ ]:
layout = go.Layout(
    plot_bgcolor='white',
    paper_bgcolor='white',
    font=dict(family='Arial', size=12),
    xaxis=dict(title='Time', gridcolor='lightgray', zerolinecolor='lightgray'),
    yaxis=dict(gridcolor='lightgray', zerolinecolor='lightgray'),
    margin=dict(l=60, r=20, t=60, b=60)
)

In [ ]:
import plotly.express as px
df.index.value_counts()

0         1
522218    1
522209    1
522210    1
522211    1
         ..
261109    1
261110    1
261111    1
261112    1
783321    1
Name: count, Length: 783322, dtype: int64

In [ ]:
from plotly.offline import plot

# **Total Borrow vs Average Borrow Amount**

In [ ]:
import pandas as pd
import plotly.express as px
import plotly.graph_objs as go
from plotly.offline import plot


fig = px.scatter(df, x='total_borrow', y='avg_borrow_amount', hover_data=['address'])
fig.update_layout(
    title='Total Borrow vs Average Borrow Amount',
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='green'
)


annotation_text = [f'Total Borrow: {x}<br>Avg Borrow: {y}' for x, y in zip(fig.data[0].x, fig.data[0].y)]
fig.update_traces(
    text=annotation_text,
    textposition='top center',
    hoverinfo='none'
)
fig.show()

# **Total Liquidation by Liquidated Status**

In [ ]:
fig = px.bar(df, x='liquidated', y='total_liquidation', color='liquidated')
fig.update_layout(
    title='Total Liquidation by Liquidated Status',
    plot_bgcolor='black',
    paper_bgcolor='black',
    font_color='green'
)


annotation_text = [f'Total Liquidation: {y}' for y in fig.data[-1].y]
fig.update_traces(
    text=annotation_text,
    textposition='top center',
    hoverinfo='none'
)

fig.show()

# **Total Deposit in Deposit Source**

In [ ]:
df['deposit_source'] = df['total_deposit'] + df['total_redeem']
fig = px.pie(df, values='deposit_source', names=['Deposit', 'Redeem'], title='Deposit Sources')
fig.show()

In [ ]:
import plotly.io as pio

In [ ]:
!pip install -U kaleido

Collecting kaleido
  Downloading kaleido-0.2.1-py2.py3-none-manylinux1_x86_64.whl (79.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 6.4 MB/s eta 0:00:00
Installing collected packages: kaleido
Successfully installed kaleido-0.2.1

In [ ]:
!pip install -U kaleido

Requirement already satisfied: kaleido in /usr/local/lib/python3.10/dist-packages (0.2.1)

In [ ]:
fig = px.scatter(df, x='total_borrow', y='avg_borrow_amount', hover_data=['address'])
fig.update_layout(title='Total Borrow vs Average Borrow Amount')
img_bytes1 = fig.to_image(format="png")

ValueError:
Image export using the "kaleido" engine requires the kaleido package,
which can be installed using pip:
    $ pip install -U kaleido

In [ ]:
fig = px.scatter(df, x='total_borrow', y='avg_borrow_amount', hover_data=['address'])
fig.update_layout(title='Total Borrow vs Average Borrow Amount')
# fig.write_image("plot1.png")

In [ ]:
pio.renderers.default = "iframe"


fig = px.scatter(df, x='total_borrow', y='avg_borrow_amount', hover_data=['address'])
fig.update_layout(title='Total Borrow vs Average Borrow Amount')
plot_div1 = pio.to_html(fig, full_html=False)

In [ ]:
print(plot_div1)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [ ]:
# fig = px.scatter(df, x="days_since_first_borrow", y="net_outstanding", color="address")
# fig.show()

In [ ]:
# fig = px.bar(df, x="address", y=["total_borrow", "total_repay", "total_deposit", "total_redeem"])
# fig.show()

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 783322 entries, 0 to 783321
Data columns (total 50 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   address                            783322 non-null  object
 1   total_borrow                       783322 non-null  float64
 2   count_borrow                       783322 non-null  int64
 3   avg_borrow_amount                  783322 non-null  float64
 4   std_borrow_amount                  783322 non-null  float64
 5   first_borrow_date                  783322 non-null  object
 6   token_borrow_mode                  783322 non-null  object
 7   borrow_amount_cv                   783322 non-null  float64
 8   total_repay                        783322 non-null  float64
 9   count_repay                        783322 non-null  float64
 10  avg_repay_amount                   783322 non-null  float64
 11  std_repay_amount                   783322 non-null  float64
 12  repay_amount_cv                    783322 non-null  float64
 13  total_deposit                      783322 non-null  float64
 14  count_deposit                      783322 non-null  float64
 15  avg_deposit_amount                 783322 non-null  float64
 16  std_deposit_amount                 783322 non-null  float64
 17  deposit_amount_cv                  783322 non-null  float64
 18  total_redeem                       783322 non-null  float64
 19  count_redeem                       783322 non-null  float64
 20  avg_redeem_amount                  783322 non-null  float64
 21  std_redeem_amount                  783322 non-null  float64
 22  redeem_amount_cv                   783322 non-null  float64
 23  total_liquidation                  783322 non-null  float64
 24  count_liquidation                  783322 non-null  float64
 25  avg_liquidation_amount             783322 non-null  float64
 26  std_liquidation_amount             783322 non-null  float64
 27  liquidation_amount_cv              783322 non-null  float64
 28  days_since_first_borrow            783322 non-null  float64
 29  net_outstanding                    783322 non-null  float64
 30  int_paid                           783322 non-null  float64
 31  net_deposits                       783322 non-null  float64
 32  count_repays_to_count_borrows      783322 non-null  float64
 33  avg_repay_to_avg_borrow            783322 non-null  float64
 34  net_outstanding_to_total_borrowed  783322 non-null  float64
 35  net_outstanding_to_total_repaid    783322 non-null  float64
 36  count_redeems_to_count_deposits    783322 non-null  float64
 37  total_redeemed_to_total_deposits   783322 non-null  float64
 38  avg_redeem_to_avg_deposit          783322 non-null  float64
 39  net_deposits_to_total_deposits     783322 non-null  float64
 40  net_deposits_to_total_redeemed     783322 non-null  float64
 41  avg_liquidation_to_avg_borrow      783322 non-null  float64
 42  dex_total_sum_added                783322 non-null  float64
 43  dex_total_sum_removed              783322 non-null  float64
 44  dex_total_sum_swapped              783322 non-null  float64
 45  liquidated                         783322 non-null  float64
 46  calc_start_time                    783322 non-null  object
 47  added_at                           783322 non-null  object
 48  total_liquidation_to_total_borrow  783322 non-null  float64
 49  __index_level_0__                  783322 non-null  int64
dtypes: float64(43), int64(2), object(5)
memory usage: 298.8+ MB

In [ ]:
!pip install dash

Collecting dash
  Downloading dash-2.17.0-py3-none-any.whl (7.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 14.2 MB/s eta 0:00:00
Requirement already satisfied: Flask<3.1,>=1.0.4 in /usr/local/lib/python3.10/dist-packages (from dash) (2.2.5)
Requirement already satisfied: Werkzeug<3.1 in /usr/local/lib/python3.10/dist-packages (from dash) (3.0.3)
Requirement already satisfied: plotly>=5.0.0 in /usr/local/lib/python3.10/dist-packages (from dash) (5.15.0)
Collecting dash-html-components==2.0.0 (from dash)
  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Collecting dash-core-components==2.0.0 (from dash)
  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Collecting dash-table==5.0.0 (from dash)
  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.10/dist-packages (from dash) (7.1.0)
Requirement already satisfied: typing-extensions>=4.1.1 in /usr/local/lib/python3.10/dist-packages (from dash) (4.11.0)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from dash) (2.31.0)
Collecting retrying (from dash)
  Downloading retrying-1.3.4-py3-none-any.whl (11 kB)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.10/dist-packages (from dash) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/dist-packages (from dash) (67.7.2)
Requirement already satisfied: Jinja2>=3.0 in /usr/local/lib/python3.10/dist-packages (from Flask<3.1,>=1.0.4->dash) (3.1.4)
Requirement already satisfied: itsdangerous>=2.0 in /usr/local/lib/python3.10/dist-packages (from Flask<3.1,>=1.0.4->dash) (2.2.0)
Requirement already satisfied: click>=8.0 in /usr/local/lib/python3.10/dist-packages (from Flask<3.1,>=1.0.4->dash) (8.1.7)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from plotly>=5.0.0->dash) (8.3.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from plotly>=5.0.0->dash) (24.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.10/dist-packages (from Werkzeug<3.1->dash) (2.1.5)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata->dash) (3.18.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->dash) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->dash) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->dash) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->dash) (2024.2.2)
Requirement already satisfied: six>=1.7.0 in /usr/local/lib/python3.10/dist-packages (from retrying->dash) (1.16.0)
Installing collected packages: dash-table, dash-html-components, dash-core-components, retrying, dash
Successfully installed dash-2.17.0 dash-core-components-2.0.0 dash-html-components-2.0.0 dash-table-5.0.0 retrying-1.3.4

In [ ]:
import pandas as pd
import plotly.express as px
import dash
import dash_core_components as dcc
import dash_html_components as html
from dash.dependencies import Input, Output


app = dash.Dash(__name__)


app.layout = html.Div([
    html.H1('Analytics Dashboard'),
    dcc.Tabs([
        dcc.Tab(label='Overview', children=[
            html.Div([
                dcc.Graph(
                    figure=px.scatter(df, x='total_borrow', y='total_repay', color='token_borrow_mode',
                                      hover_data=['address', 'avg_borrow_amount', 'avg_repay_amount'])
                ),
                dcc.Graph(
                    figure=px.histogram(df, x='days_since_first_borrow', color='liquidated')
                )
            ], style={'display': 'flex'}),
            html.Div([
                dcc.Graph(
                    figure=px.pie(df, values='count_liquidation', names='token_borrow_mode')
                ),
                dcc.Graph(
                    figure=px.bar(df, x='token_borrow_mode', y='net_outstanding', color='liquidated')
                )
            ], style={'display': 'flex'})
        ]),
        dcc.Tab(label='Liquidations', children=[
            html.Div([
                dcc.Graph(
                    figure=px.scatter(df, x='total_borrow', y='total_liquidation', color='liquidated',
                                      hover_data=['address', 'avg_liquidation_amount', 'avg_liquidation_to_avg_borrow'])
                ),
                dcc.Graph(
                    figure=px.histogram(df, x='std_liquidation_amount', color='liquidated')
                )
            ], style={'display': 'flex'})
        ]),
        dcc.Tab(label='Transactions', children=[
            html.Div([
                dcc.Graph(
                    figure=px.scatter(df, x='total_deposit', y='total_redeem', color='token_borrow_mode',
                                      hover_data=['address', 'avg_deposit_amount', 'avg_redeem_amount'])
                ),
                dcc.Graph(
                    figure=px.bar(df, x='token_borrow_mode', y='net_deposits', color='liquidated')
                )
            ], style={'display': 'flex'})
        ])
    ])
])


if __name__ == '__main__':
    app.run_server(debug=True)

<ipython-input-29-c8ae6a28861a>:4: UserWarning:


The dash_core_components package is deprecated. Please replace
`import dash_core_components as dcc` with `from dash import dcc`

<ipython-input-29-c8ae6a28861a>:5: UserWarning:


The dash_html_components package is deprecated. Please replace
`import dash_html_components as html` with `from dash import html`

In [ ]:

app = dash.Dash(name)
app.layout = html.Div([
dcc.Graph(id='borrowing-trends'),
dcc.Dropdown(
id='token-dropdown',
options=[{'label': token, 'value': token} for token in df['token_borrow_mode'].unique()],
value='DAI'
)
])
@app.callback(
Output('borrowing-trends', 'figure'),
[Input('token-dropdown', 'value')])
def update_graph(selected_token):
    filtered_df = df[df['token_borrow_mode'] == selected_token]
    trace = go.Scatter(
    x=filtered_df['days_since_first_borrow'],
    y=filtered_df['total_borrow'],
    mode='lines',
    name='Total Borrowed'
    )
    layout = go.Layout(
    title=f'Borrowing Trends for {selected_token}',
    xaxis=dict(title='Days Since First Borrow'),
    yaxis=dict(title='Total Borrowed')
    )
    return {'data': [trace], 'layout': layout}
if name == 'main':
   app.run_server(debug=True)

In [ ]:
app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Graph(id='liquidation-stats'),
    dcc.RangeSlider(
        id='liquidation-range-slider',
        min=df['avg_liquidation_amount'].min(),
        max=df['avg_liquidation_amount'].max(),
        value=[df['avg_liquidation_amount'].min(), df['avg_liquidation_amount'].max()],
        marks={
            int(value): str(value) for value in range(int(df['avg_liquidation_amount'].min()), int(df['avg_liquidation_amount'].max()) + 1, 10)
        }
    )
])

@app.callback(
    Output('liquidation-stats', 'figure'),
    [Input('liquidation-range-slider', 'value')])
def update_graph(selected_range):
    filtered_df = df[(df['avg_liquidation_amount'] >= selected_range[0]) & (df['avg_liquidation_amount'] <= selected_range[1])]
    trace1 = go.Histogram(
        x=filtered_df['avg_liquidation_amount'],
        name='Average Liquidation Amount'
    )
    trace2 = go.Histogram(
        x=filtered_df['count_liquidation'],
        name='Count of Liquidations'
    )
    layout = go.Layout(
        title='Liquidation Statistics',
        xaxis=dict(title='Value'),
        yaxis=dict(title='Count'),
        bargap=0.1,
        barmode='overlay'
    )
    return {'data': [trace1, trace2], 'layout': layout}

if __name__ == '__main__':
    app.run_server(debug=True)

In [ ]:
app = dash.Dash(__name__)

app.layout = html.Div([
    dcc.Graph(id='repay-borrow-ratio'),
    dcc.Slider(
        id='ratio-slider',
        min=df['count_repays_to_count_borrows'].min(),
        max=df['count_repays_to_count_borrows'].max(),
        value=df['count_repays_to_count_borrows'].mean(),
        marks={
            int(value): str(value) for value in range(int(df['count_repays_to_count_borrows'].min()), int(df['count_repays_to_count_borrows'].max()) + 1, 10)
        }
    )
])

@app.callback(
    Output('repay-borrow-ratio', 'figure'),
    [Input('ratio-slider', 'value')])
def update_graph(selected_ratio):
    filtered_df = df[df['count_repays_to_count_borrows'] >= selected_ratio]
    trace = go.Histogram(
        x=filtered_df['count_repays_to_count_borrows'],
        name='Count of Repays to Count of Borrows'
    )
    layout = go.Layout(
        title='Ratio of Repays to Borrows',
        xaxis=dict(title='Ratio'),
        yaxis=dict(title='Count')
    )
    return {'data': [trace], 'layout': layout}

if __name__ == '__main__':
    app.run_server(debug=True)

In [ ]:
app = dash.Dash(name)
app.layout = html.Div([
dcc.Graph(id='deposit-redeem-scatter'),
dcc.RangeSlider(
id='deposit-redeem-range-slider',
min=df['net_deposits'].min(),
max=df['net_deposits'].max(),
value=[df['net_deposits'].min(), df['net_deposits'].max()],
marks={
int(value): str(value) for value in range(int(df['net_deposits'].min()), int(df['net_deposits'].max()) + 1, 10)
    }
  )
])
@app.callback(
Output('deposit-redeem-scatter', 'figure'),
[Input('deposit-redeem-range-slider', 'value')])
def update_graph(selected_range):
    filtered_df = df[(df['net_deposits'] >= selected_range[0]) & (df['net_deposits'] <= selected_range[1])]
    trace1 = go.Scatter(
    x=filtered_df['total_deposit'],
    y=filtered_df['total_redeem'],
    mode='markers',
    name='Deposits vs Redeems'
    )
    layout = go.Layout(
    title='Deposit and Redeem Amounts',
    xaxis=dict(title='Total Deposit'),
    yaxis=dict(title='Total Redeem')
    )
    return {'data': [trace1], 'layout': layout}
if name == 'main':
    app.run_server(debug=True)